# 流量标签在各种通道间(http/rpc/消息队列等)传递的配置
tag.transmission.config:
  # 是否开启流量标签透传功能, 默认为true
  enabled: true
  # 需要透传的流量标签的key的匹配规则, 支持精确、前缀、后缀匹配
  matchRule:
    # 精确匹配规则，为列表形式。若列表中的某个元素与标签键相同，则表示该标签需要透传。示例值为["id", "name"]
    exact: ["id", "name"]
    # 前缀匹配规则，为列表形式。若列表中的某个元素是标签键的前缀，则表示该标签需要透传。示例值为["x-sermant-"]
    prefix: ["x-sermant-"]
    # 后缀匹配规则，为列表形式。若列表中的某个元素是标签键的后缀，则表示该标签需要透传。示例值为["-sermant"]
    suffix: ["-sermant"]

# 跨线程传递标签的配置
crossthread.config:
  # 是否需要在new Thread时透传流量标签，默认开启
  enabled-thread: true
  # 是否需要在普通线程池创建新的线程任务时透传流量标签，默认开启
  enabled-thread-pool: true
  # 是否需要在定时线程池创建新的线程任务时透传流量标签，默认开启
  enabled-scheduler: true