name: "Agent-core Dynamic Test"
description: "Auto test for agent-core dynamic"
runs:
  using: "composite"
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/agentcore-test
    - name: start applications
      shell: bash
      env:
        dynamic.config.serverAddress: 127.0.0.1:2181
        dynamic.config.dynamicConfigType: ZOOKEEPER
        service.meta.project: TestAgentCore
      run: |
        nohup java -jar \
        sermant-agent-${{ env.sermantVersion }}/agent/agentcore-test-application-1.0.0-jar-with-dependencies.jar > ${{ env.logDir
        }}/agentcore-test.log 2>&1 &
    - name: waiting for agentcore services start
      shell: bash
      run: |
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8915/ping 120
    - name: (install agent) modify plugins file
      shell: bash
      run: |
        sed -i '/  passive:/a \  - dynamic-test-first-plugin' sermant-agent-${{ env.sermantVersion }}/agent/config/plugins.yaml
        sed -i '/  passive:/a \  - dynamic-test-second-plugin' sermant-agent-${{ env.sermantVersion }}/agent/config/plugins.yaml
    - name: (install agent) dynamic install agent
      shell: bash
      run: curl http://127.0.0.1:8915/ping?agentPath=sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar&configParam=NULL
    - name: (install plugin) dynamic install plugin
      shell: bash
      run: curl http://127.0.0.1:8915/ping?agentPath=sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar&configParam=INSTALL-PLUGINS:dynamic-test-first-plugin/dynamic-test-second-plugin
    - name: (install plugin) test install plugin
      shell: bash
      run: mvn test -Dsermant.agentcore.test.type=INSTALL_PLUGIN --file sermant-integration-tests/agentcore-test/agentcore-integration-test/pom.xml
    - name: (uninstall plugin) dynamic uninstall plugin
      shell: bash
      run: curl http://127.0.0.1:8915/ping?agentPath=sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar&configParam=UNINSTALL-PLUGINS:dynamic-test-first-plugin
    - name: (uninstall plugin) test uninstall plugin
      shell: bash
      run: mvn test -Dsermant.agentcore.test.type=UNINSTALL_PLUGIN --file sermant-integration-tests/agentcore-test/agentcore-integration-test/pom.xml
    - name: (uninstall agent) dynamic uninstall agent
      shell: bash
      run: curl http://127.0.0.1:8915/ping?agentPath=sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar&configParam=UNINSTALL-AGENT
    - name: (uninstall agent) test uninstall agent
      shell: bash
      run: mvn test -Dsermant.agentcore.test.type=UNINSTALL_AGENT --file sermant-integration-tests/agentcore-test/agentcore-integration-test/pom.xml
    - name: (reinstall agent) dynamic reinstall agent
      shell: bash
      run: curl http://127.0.0.1:8915/ping?agentPath=sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar&configParam=INSTALL-PLUGINS:dynamic-test-first-plugin/dynamic-test-second-plugin
    - name: (reinstall agent) test reinstall agent
      shell: bash
      run: mvn test -Dsermant.agentcore.test.type=REINSTALL_AGENT --file sermant-integration-tests/agentcore-test/agentcore-integration-test/pom.xml

    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: agentcore
    - name: Stop JAR Service
      shell: bash
      run: pkill -f "java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar -jar sermant-agent-${{ env.sermantVersion }}/agent/agentcore-test-application-1.0.0-jar-with-dependencies.jar"
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: agentcore-test-logs
        path: |
          ./*.log
          ./logs/**
        if-no-files-found: warn
        retention-days: 2
